spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/${USER_SERVICE_DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    discovery:
      enabled: false 
  eureka:
    client:
      enabled: false 
      fetchRegistry: false
      registerWithEureka: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info,httptrace,prometheus"
  metrics:
    tags:
      application: ${spring.application.name}-dev

info:
  app:
    name: "user-service-dev"
    description: "User service app (Local Development Profile)"
    version: "1.0.0-DEV"

logging:
  level:
    tracz:
      userservice: debug
    org:
      springframework: debug 
